### ISSUE TITLE
slice out of bound when extract .exe ico

### ISSUE THREAD

**Issue by WAY29** [orcastor/fico#7]
panic: runtime error: slice bounds out of range [:2147483716] with capacity 174080

goroutine 1 [running]:
github.com/orcastor/fico.parseDir({0xc000100000, 0x2a800, 0x2a800}, 0x0, {0x0, 0x0}, 0xa764000)
        golang/pkg/mod/github.com/orcastor/fico@v0.0.0-20241115153506-4e6e1f6f0b5e/fico.go:488 +0x4ba
github.com/orcastor/fico.PE2ICO({0x84d028, 0xc000072098}, {0x81839f?, 0x1d40930d768?}, {0x0, 0x0, 0x0})
        golang/pkg/mod/github.com/orcastor/fico@v0.0.0-20241115153506-4e6e1f6f0b5e/fico.go:604 +0x14f
github.com/orcastor/fico.F2ICO({0x84d028, 0xc000072098}, {0x81839f, 0x1f}, {0x0, 0x0, 0x0})
        golang/pkg/mod/github.com/orcastor/fico@v0.0.0-20241115153506-4e6e1f6f0b5e/fico.go:46 +0x125
main.main()
        golang/src/gotest/fico/fico.go:226 +0x52
exit status 2

**Comment by WAY29** [comment]
try some .exe on my computer and got many slice bounds out of range
